name: Build React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: build-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          npm install

      - name: Build
        run: |
         cd ${{ github.workspace }}
         npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/
